language: python
python: 3.5
install:
- pip install -r requirements-dev.txt
- python setup.py install
script: py.test
deploy:
  provider: pypi
  user: tonyfast
  password:
    secure: EmIhPiD6ALM+QC5m68FY4piCQ8WjRck9DKWubgcqblhevwYYQsOBQpUsUguxQ07NqUIN0JOHcZlLYsCnFySOIDFSp9cdsbzvCOZpkbOOvtLm2mLUQKiruSEdit92IVmSJInFEKCOacWjbwCza6LnOsolebWbn/DCMk93d5l5MLq7kG8eV3PzRDxogUW06fRmd9RQ9vsSsxu0jlhEjRPpvg4Bp0/VXiKbrHEx3Yn5lyJasm22Voi7PiVz7xFpcqiEfjiZwo/4aqsBA99eOHAFOa21f0knSBjVt0jA98uIeHz4R0c59qFeZIrqDSbtfT/EWx0uQxFXtXiPV9Nk5b5TnYoxuaaDQ+yO3GzOuuGvaDooRB1a77tmS0lOzdP8Dg/O/Tia7J7JqZHvbY+Md/KUrit7BkRN88Qn1tykVy+NHq8zUKIxVJHQ1OLJZlICY6SNrUtLljE3BcjZiIn+K/zKgoA3xOzlewzAw7PRvddUbHYnrUlnU091C/ubP3R4gOm8E/SZvZFprAED3tcsZ13wqFguJzY/bmt4RWS0+cB5G0apuhwXpBdLKj20z1qOrzg80ptpaQOlC5KiQW0sTS0xDpNZGGjrdkIWscgCumym3sVlbYb4xLi1HidMQusc93lCgv/J7mNsaseTgSp35NemSHdWSUAnLN4Zpc/Q9BtwJlc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: tonyfast/whatever-forever
